public enum KeyCodeIndicatorType
{
	WEAPON_PRIMARY = 0,
	WEAPON_BACKUP = 1,
	WEAPON_MELEE = 2,
	WEAPON_SPECIAL = 3,
	WEAPON_PREMIUM = 4,
	CONSUMABLE_INVISIBLE = 5,
	CONSUMABLE_TURRET = 6,
	CONSUMABLE_JETPACK = 7,
	CONSUMABLE_ROBOT = 8,
	ADD_AMMO = 9,
	ADD_HEALTH = 10,
	USE_GRENADE = 11,
	TAB = 12,
}
