using UnityEngine;
using System.Collections.Generic;

public class NetworkStartTable : MonoBehaviour
{
	public string pixelBookID;
	public bool isShowAvard;
	public GameObject guiObj;
	public NetworkStartTableNGUIController networkStartTableNGUIController;
	public bool isRegimVidos;
	public Player_move_c currentPlayerMoveCVidos;
	public string playerVidosNick;
	public string playerVidosClanName;
	public Texture playerVidosClanTexture;
	public GameObject currentCamPlayer;
	public GameObject currentFPSPlayer;
	public GameObject currentGameObjectPlayer;
	public bool isGoRandomRoom;
	public Texture mySkin;
	public List<GameObject> zombiePrefabs;
	public GameObject tempCam;
	public GameObject zombieManagerPrefab;
	public Texture2D serverLeftTheGame;
	public ExperienceController experienceController;
	public bool isDeadInHungerGame;
	public bool isIwin;
	public int myCommand;
	public int myCommandOld;
	public Texture myClanTexture;
	public string myClanID;
	public string myClanName;
	public string myClanLeaderID;
	public bool isDrawInHanger;
	public GUIStyle labelStyle;
	public GUIStyle messagesStyle;
	public GUIStyle ozidanieStyle;
	public GameObject _purchaseActivityIndicator;
	public WeaponManager _weaponManager;
	public bool _showTable;
	public string nickPobeditelya;
	public bool _isShowNickTable;
	public bool runGame;
	public GameObject[] zoneCreatePlayer;
	public bool isDrawInDeathMatch;
	public bool showDisconnectFromServer;
	public bool showDisconnectFromMasterServer;
	public string NamePlayer;
	public string[] oldSpisokName;
	public string[] oldCountLilsSpisok;
	public string[] oldScoreSpisok;
	public int[] oldSpisokRanks;
	public string[] oldSpisokNameBlue;
	public string[] oldCountLilsSpisokBlue;
	public int[] oldSpisokRanksBlue;
	public string[] oldSpisokNameRed;
	public string[] oldCountLilsSpisokRed;
	public string[] oldScoreSpisokRed;
	public string[] oldScoreSpisokBlue;
	public int[] oldSpisokRanksRed;
	public bool[] oldIsDeadInHungerGame;
	public string[] oldSpisokPixelBookID;
	public string[] oldSpisokPixelBookIDBlue;
	public string[] oldSpisokPixelBookIDRed;
	public Texture[] oldSpisokMyClanLogo;
	public Texture[] oldSpisokMyClanLogoBlue;
	public Texture[] oldSpisokMyClanLogoRed;
	public int oldIndexMy;
}
