using UnityEngine;

public class Player_move_c : MonoBehaviour
{
	public enum TypeKills
	{
		none = 0,
		himself = 1,
		headshot = 2,
		explosion = 3,
		zoomingshot = 4,
		flag = 5,
		grenade = 6,
		grenade_hell = 7,
		turret = 8,
		killTurret = 9,
		mech = 10,
	}

	public PlayerScoreController myScoreController;
	public float timeBuyHealth;
	public float armorSynch;
	public bool isReloading;
	public bool isPlacemarker;
	public Player_move_c placemarkerMoveC;
	public ParticleBonuse[] bonusesParticles;
	public GameObject particleBonusesPoint;
	public Transform myTransform;
	public Transform myPlayerTransform;
	public int myPlayerID;
	public SkinName mySkinName;
	public GameObject mechPoint;
	public GameObject mechBody;
	public Animation mechGunAnimation;
	public Animation mechBodyAnimation;
	public WeaponSounds mechWeaponSounds;
	public ParticleSystem[] flashMech;
	public GameObject fpsPlayerBody;
	public GameObject myCurrentWeapon;
	public WeaponSounds myCurrentWeaponSounds;
	public GameObject mechExplossion;
	public AudioClip shootMechClip;
	public SkinnedMeshRenderer playerBodyRenderer;
	public SkinnedMeshRenderer mechBodyRenderer;
	public SkinnedMeshRenderer mechHandRenderer;
	public SkinnedMeshRenderer mechGunRenderer;
	public CapsuleCollider bodyCollayder;
	public CapsuleCollider headCollayder;
	public Material[] mechGunMaterials;
	public Material[] mechBodyMaterials;
	public bool isMechActive;
	public AudioClip flagGetClip;
	public AudioClip flagLostClip;
	public AudioClip flagScoreEnemyClip;
	public AudioClip flagScoreMyCommandClip;
	public float deltaAngle;
	public GameObject playerDeadPrefab;
	public ThirdPersonNetwork1 myPersonNetwork;
	public GameObject grenadePrefab;
	public GameObject turretPrefab;
	public GameObject turretPoint;
	public GameObject currentTurret;
	public float[] liveMechByTier;
	public bool isImVisible;
	public bool isWeaponSet;
	public NetworkStartTableNGUIController networkStartTableNGUIController;
	public GameObject invisibleParticle;
	public bool isInvisible;
	public float maxTimeSetTimerShow;
	public bool isRegenerationLiveZel;
	public bool isRegenerationLiveCape;
	public bool isCaptureFlag;
	public Camera myCamera;
	public Camera gunCamera;
	public GameObject hatsPoint;
	public GameObject capesPoint;
	public GameObject flagPoint;
	public GameObject bootsPoint;
	public GameObject armorPoint;
	public bool isZooming;
	public AudioClip headShotSound;
	public AudioClip flagCaptureClip;
	public AudioClip flagPointClip;
	public GameObject headShotParticle;
	public GameObject healthParticle;
	public GameObject chatViewer;
	public GUISkin MySkin;
	public GameObject myTable;
	public int AimTextureWidth;
	public int AimTextureHeight;
	public Transform GunFlash;
	public bool showGUIUnlockFullVersion;
	public float timeHingerGame;
	public bool killed;
	public ZombiManager zombiManager;
	public NickLabelController myNickLabelController;
	public visibleObjPhoton visibleObj;
	public string textChat;
	public bool showGUI;
	public bool showRanks;
	public GUIStyle combatRifleStyle;
	public GUIStyle goldenEagleInappStyle;
	public GUIStyle magicBowInappStyle;
	public GUIStyle spasStyle;
	public GUIStyle axeStyle;
	public GUIStyle famasStyle;
	public GUIStyle glockStyle;
	public GUIStyle chainsawStyle;
	public GUIStyle scytheStyle;
	public GUIStyle shovelStyle;
	public bool showChat;
	public bool showChatOld;
	public bool showRanksOld;
	public int myCommand;
	public float timerShowUp;
	public float timerShowLeft;
	public float timerShowDown;
	public float timerShowRight;
	public string myIp;
	public TrainingController trainigController;
	public bool isKilled;
	public bool theEnd;
	public string nickPobeditel;
	public Texture hitTexture;
	public Texture _skin;
	public float showNoInetTimer;
	public int maxCountKills;
	public Texture sendTek;
	public Texture sendUstanovlenii;
	public bool isMulti;
	public bool isInet;
	public bool isMine;
	public bool isCompany;
	public bool isCOOP;
	public int multiKill;
	public FlagController flag1;
	public FlagController flag2;
	public FlagController myFlag;
	public FlagController enemyFlag;
	public bool isStartAngel;
	public GameObject _label;
	public bool isImmortality;
	public float healthMod;
	public int AmmoBoxWidth;
	public int AmmoBoxHeight;
	public int AmmoBoxOffset;
	public int ScoreBoxWidth;
	public int ScoreBoxHeight;
	public int ScoreBoxOffset;
	public float[] timerShow;
	public AudioClip deadPlayerSound;
	public AudioClip damagePlayerSound;
	public GameObject[] zoneCreatePlayer;
	public GUIStyle ScoreBox;
	public GUIStyle AmmoBox;
	public GUIStyle sliderSensStyle;
	public GUIStyle thumbSensStyle;
	public GameObject _player;
	public GameObject bulletPrefab;
	public GameObject bulletPrefabRed;
	public GameObject _bulletSpawnPoint;
	public GameObject _purchaseActivityIndicator;
	public GUIStyle puliInApp;
	public InGameGUI inGameGUI;
	public GUIStyle healthInApp;
	public GUIStyle crystalSwordInapp;
	public GUIStyle elixirInapp;
	public GUIStyle pulemetInApp;
	public bool _isInappWinOpen;
	public GUIStyle armorStyle;
	public float slideMagnitudeX;
	public float slideMagnitudeY;
	public AudioClip ChangeWeaponClip;
	public AudioClip ChangeGrenadeClip;
	public AudioClip WeaponBonusClip;
	public PhotonView photonView;
	public AudioClip clickShop;
	public bool isTraining;
	public bool isSurvival;
	public string myTableId;
	public GameObject jetPackPoint;
	public GameObject jetPackPointMech;
	public ParticleSystem[] jetPackParticle;
	public GameObject jetPackSound;
	public bool isGrenadePress;
}
